In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv( r"D:\FMCG-Sales-Analysis\FMCG_SALE_DATA.csv")

df.head(10)

,Order_ID,Company_Name,Order_Date,State,City,City_Tier,Store_Type,Product_Category,Product_Name,Quantity_Sold,Unit_Price_INR,Payment_Method,GST_Rate_Pct,Discount_Applied_Pct,Delivery_Days
0,IND-2024-100000,Reliance Jio Infocomm,26-Jan-24,Telangana,Hyderabad,Tier 1,Supermarket,Packaged Food,Parle-G Gold Biscuits 1kg,22,140,UPI,5,5,2
1,IND-2024-100001,Tata Consultancy Services,28-07-2025,Bihar,Patna,Tier 3,Quick-Commerce Hub,Household Supplies,Vim Dishwash Liquid Gel 750ml,9,NaN,Cash / COD,18,10,3
2,IND-2024-100002,Mahindra & Mahindra,14-04-2024,Uttar Pradesh,Lucknow,Tier 2,Kirana Store,Dairy & Staples,Aashirvaad Shuddh Atta 10kg,20,440,UPI,0,15,1
3,IND-2024-100003,Flipkart India,05-01-2025,Karnataka,Bengaluru,Tier 1,Kirana Store,Dairy & Staples,Amul Pasteurized Butter 500g,3,275,Credit Card,0,10,2
4,IND-2024-100004,Wipro Enterprise,17-Nov-25,Karnataka,Bengaluru,Tier 1,Supermarket,Beverages,Nescafe Classic Instant Coffee 100g,6,290,Debit Card,18,10,7
5,IND-2024-100005,Tata Consumer Products,22-08-2024,Gujarat,Ahmedabad,Tier 2,Quick-Commerce Hub,Beverages,Nescafe Classic Instant Coffee 100g,19,290,Credit Card,18,25,4
6,IND-2024-100006,Bharti Airtel,09-Sep-24,Madhya Pradesh,Indore,Tier 2,Quick-Commerce Hub,Personal Care,Dettol Antiseptic Soap 125g (Pack of 4),12,210,UPI,18,0,2
7,IND-2024-100007,ITC Limited,02-09-2025,Uttar Pradesh,Lucknow,Tier 2,Quick-Commerce Hub,Personal Care,Dove Hair Fall Rescue Shampoo 650ml,17,495,UPI,18,20,7
8,IND-2024-100008,Mahindra & Mahindra,24-Apr-24,Uttar Pradesh,Lucknow,Tier 2,Supermarket,Dairy & Staples,Amul Pasteurized Butter 500g,17,275,Net Banking,0,20,5
9,IND-2024-100009,Bajaj Finserv B2B,14-06-2024,Madhya Pradesh,Indore,Tier 2,Hypermarket,Packaged Food,Parle-G Gold Biscuits 1kg,12,140,UPI,5,20,1

In [3]:
df.tail()

,Order_ID,Company_Name,Order_Date,State,City,City_Tier,Store_Type,Product_Category,Product_Name,Quantity_Sold,Unit_Price_INR,Payment_Method,GST_Rate_Pct,Discount_Applied_Pct,Delivery_Days
50745,IND-2024-123493,Tech Mahindra,16-05-2025,Madhya Pradesh,Indore,Tier 2,Kirana Store,Dairy & Staples,Amul Pasteurized Butter 500g,8,275,Credit Card,0,20,3
50746,IND-2024-115789,Tata Consumer Products,04-01-2024,Uttar Pradesh,Lucknow,Tier 2,Hypermarket,Beverages,Nescafe Classic Instant Coffee 100g,15,290,Net Banking,18,20,6
50747,IND-2024-135779,Godrej Consumer Products,NaN,Bihar,Patna,Tier 3,Quick-Commerce Hub,Packaged Food,Maggi 2-Min Noodles 420g,24,120,Credit Card,5,20,4
50748,IND-2024-111980,Bajaj Finserv B2B,06-May-24,Uttar Pradesh,Lucknow,Tier 2,Kirana Store,Beverages,Nescafe Classic Instant Coffee 100g,7,NaN,Cash / COD,18,25,2
50749,IND-2024-144905,Mahindra & Mahindra,03-Jun-25,Bihar,Patna,Tier 3,Hypermarket,Dairy & Staples,Aashirvaad Shuddh Atta 10kg,14,440,Cash / COD,0,15,5

In [4]:
df.shape

(50750, 15)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50750 entries, 0 to 50749
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Order_ID              50750 non-null  str
 1   Company_Name          50750 non-null  str
 2   Order_Date            38009 non-null  str
 3   State                 50750 non-null  str
 4   City                  50750 non-null  str
 5   City_Tier             50750 non-null  str
 6   Store_Type            50750 non-null  str
 7   Product_Category      50750 non-null  str
 8   Product_Name          50750 non-null  str
 9   Quantity_Sold         50750 non-null  int64
 10  Unit_Price_INR        49268 non-null  str
 11  Payment_Method        49702 non-null  str
 12  GST_Rate_Pct          50750 non-null  int64
 13  Discount_Applied_Pct  50750 non-null  int64
 14  Delivery_Days         50750 non-null  int64
dtypes: int64(4), str(11)
memory usage: 12.1 MB

In [6]:
df.describe()

       Quantity_Sold  GST_Rate_Pct  Discount_Applied_Pct  Delivery_Days
count   50750.000000  50750.000000          50750.000000   50750.000000
mean       12.656985     10.535094             12.522069      14.322443
std         7.874434      7.704949              8.523726     100.887497
min       -25.000000      0.000000              0.000000       1.000000
25%         7.000000      5.000000              5.000000       2.000000
50%        13.000000     18.000000             15.000000       4.000000
75%        19.000000     18.000000             20.000000       6.000000
max        25.000000     18.000000             25.000000     999.000000

In [7]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
50745     True
50746     True
50747     True
50748     True
50749     True
Length: 50750, dtype: bool

In [8]:
df.duplicated().sum()

np.int64(750)

In [9]:
print("Duplicate Rows Count:", df.duplicated().sum())

Duplicate Rows Count: 750

In [10]:
print("\n=== MISSING (NULL) VALUES ===")
print(df.isnull().sum())

=== MISSING (NULL) VALUES ===
Order_ID                    0
Company_Name                0
Order_Date              12741
State                       0
City                        0
City_Tier                   0
Store_Type                  0
Product_Category            0
Product_Name                0
Quantity_Sold               0
Unit_Price_INR           1482
Payment_Method           1048
GST_Rate_Pct                0
Discount_Applied_Pct        0
Delivery_Days               0
dtype: int64

In [11]:
df = df.drop_duplicates()

In [12]:
print("\n=== DATA TYPES ===")
print(df.dtypes)

=== DATA TYPES ===
Order_ID                  str
Company_Name              str
Order_Date                str
State                     str
City                      str
City_Tier                 str
Store_Type                str
Product_Category          str
Product_Name              str
Quantity_Sold           int64
Unit_Price_INR            str
Payment_Method            str
GST_Rate_Pct            int64
Discount_Applied_Pct    int64
Delivery_Days           int64
dtype: object

In [13]:
df.Order_Date

0         26-Jan-24
1        28-07-2025
2        14-04-2024
3        05-01-2025
4         17-Nov-25
            ...
49995    26-07-2025
49996    04-12-2024
49997     20-Sep-24
49998     14-Mar-25
49999    12-12-2025
Name: Order_Date, Length: 50000, dtype: str

In [14]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='mixed', errors='coerce').bfill().ffill()

In [15]:
# Fix: Pass dayfirst=True to specify DD/MM/YYYY format explicitly
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='mixed', dayfirst=True).dt.strftime('%d/%m/%Y')

In [16]:
df['Store_Type'] = df['Store_Type'].str.title().str.strip()

In [17]:
print("\n=== CATEGORICAL INCONSISTENCIES (Store_Type) ===")
print(df['Store_Type'].unique())

=== CATEGORICAL INCONSISTENCIES (Store_Type) ===
<ArrowStringArray>
['Supermarket', 'Quick-Commerce Hub', 'Kirana Store', 'Hypermarket']
Length: 4, dtype: str

In [18]:
df['Store_Type'] = df['Store_Type'].str.title().str.strip()

In [19]:
df['Unit_Price_INR'] = pd.to_numeric(df['Unit_Price_INR'].astype(str).str.replace('₹', '').str.strip(), errors='coerce')
df['Unit_Price_INR'] = df.groupby('Product_Name')['Unit_Price_INR'].transform(lambda x: x.fillna(x.median()))

In [20]:
df['Quantity_Sold'] = df['Quantity_Sold'].abs()
df['Payment_Method'] = df['Payment_Method'].fillna('Unknown')

In [21]:
df['Delivery_Days'] = df['Delivery_Days'].apply(lambda x: 7 if x > 30 else x)

In [22]:
df['Gross_Amount'] = df['Quantity_Sold'] * df['Unit_Price_INR']
df['Discount_Amount'] = df['Gross_Amount'] * (df['Discount_Applied_Pct'] / 100)
df['Net_Sales_INR'] = df['Gross_Amount'] - df['Discount_Amount']

In [23]:
print("\n===  ANOMALIES & OUTLIERS ===")
print("Quantity Range (Min to Max):", df['Quantity_Sold'].min(), "to", df['Quantity_Sold'].max())
print("Delivery Days Range (Min to Max):", df['Delivery_Days'].min(), "to", df['Delivery_Days'].max())

===  ANOMALIES & OUTLIERS ===
Quantity Range (Min to Max): 1 to 25
Delivery Days Range (Min to Max): 1 to 7

In [24]:
df.to_csv("cleaned_Fmcg_Sales.csv", index=False)
print("Cleaning complete! File saved successfully.")

Cleaning complete! File saved successfully.

# COMPLETED